cd ../
# vanilla model
python fairlib --dataset Moji --emb_size 2304 --num_classes 2 --num_groups 2 --batch_size 128 --lr 0.003 --dropout 0.1 --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --exp_id opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_vanilla_1 --device_id 0&
python fairlib --dataset Moji --emb_size 2304 --num_classes 2 --num_groups 2 --batch_size 128 --lr 0.003 --dropout 0.1 --data_dir ../fl_scripts/data/deepmoji --base_seed 2 --exp_id opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_vanilla_2 --device_id 1&
python fairlib --dataset Moji --emb_size 2304 --num_classes 2 --num_groups 2 --batch_size 128 --lr 0.003 --dropout 0.1 --data_dir ../fl_scripts/data/deepmoji --base_seed 3 --exp_id opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_vanilla_3 --device_id 2; wait;
python fairlib --dataset Moji --emb_size 2304 --num_classes 2 --num_groups 2 --batch_size 128 --lr 0.003 --dropout 0.1 --data_dir ../fl_scripts/data/deepmoji --base_seed 4 --exp_id opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_vanilla_4 --device_id 0&
python fairlib --dataset Moji --emb_size 2304 --num_classes 2 --num_groups 2 --batch_size 128 --lr 0.003 --dropout 0.1 --data_dir ../fl_scripts/data/deepmoji --base_seed 5 --exp_id opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_vanilla_5 --device_id 1&
# adv model
python fairlib --dataset Moji --emb_size 2304 --num_classes 2 --num_groups 2 --batch_size 128 --lr 0.003 --dropout 0.1 --early_stopping_criterion max_balanced_dto --adv_lambda 10.0 --adv_debiasing --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --exp_id opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_adv_1 --device_id 2; wait;
python fairlib --dataset Moji --emb_size 2304 --num_classes 2 --num_groups 2 --batch_size 128 --lr 0.003 --dropout 0.1 --early_stopping_criterion max_balanced_dto --adv_lambda 10.0 --adv_debiasing --data_dir ../fl_scripts/data/deepmoji --base_seed 2 --exp_id opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_adv_2 --device_id 0&
python fairlib --dataset Moji --emb_size 2304 --num_classes 2 --num_groups 2 --batch_size 128 --lr 0.003 --dropout 0.1 --early_stopping_criterion max_balanced_dto --adv_lambda 10.0 --adv_debiasing --data_dir ../fl_scripts/data/deepmoji --base_seed 3 --exp_id opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_adv_3 --device_id 1&
python fairlib --dataset Moji --emb_size 2304 --num_classes 2 --num_groups 2 --batch_size 128 --lr 0.003 --dropout 0.1 --early_stopping_criterion max_balanced_dto --adv_lambda 10.0 --adv_debiasing --data_dir ../fl_scripts/data/deepmoji --base_seed 4 --exp_id opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_adv_4 --device_id 2; wait
python fairlib --dataset Moji --emb_size 2304 --num_classes 2 --num_groups 2 --batch_size 128 --lr 0.003 --dropout 0.1 --early_stopping_criterion max_balanced_dto --adv_lambda 10.0 --adv_debiasing --data_dir ../fl_scripts/data/deepmoji --base_seed 5 --exp_id opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_adv_5 --device_id 0&

# BTEO model
python fairlib --dataset Moji --emb_size 2304 --num_classes 2 --num_groups 2 --batch_size 128 --lr 0.003 --dropout 0.1 --early_stopping_criterion max_balanced_dto --BT Reweighting --BTObj EO --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --exp_id opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_bteo_1 --device_id 1&
python fairlib --dataset Moji --emb_size 2304 --num_classes 2 --num_groups 2 --batch_size 128 --lr 0.003 --dropout 0.1 --early_stopping_criterion max_balanced_dto --BT Reweighting --BTObj EO --data_dir ../fl_scripts/data/deepmoji --base_seed 2 --exp_id opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_bteo_2 --device_id 2; wait;
python fairlib --dataset Moji --emb_size 2304 --num_classes 2 --num_groups 2 --batch_size 128 --lr 0.003 --dropout 0.1 --early_stopping_criterion max_balanced_dto --BT Reweighting --BTObj EO --data_dir ../fl_scripts/data/deepmoji --base_seed 3 --exp_id opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_bteo_3 --device_id 0&
python fairlib --dataset Moji --emb_size 2304 --num_classes 2 --num_groups 2 --batch_size 128 --lr 0.003 --dropout 0.1 --early_stopping_criterion max_balanced_dto --BT Reweighting --BTObj EO --data_dir ../fl_scripts/data/deepmoji --base_seed 4 --exp_id opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_bteo_4 --device_id 1&
python fairlib --dataset Moji --emb_size 2304 --num_classes 2 --num_groups 2 --batch_size 128 --lr 0.003 --dropout 0.1 --early_stopping_criterion max_balanced_dto --BT Reweighting --BTObj EO --data_dir ../fl_scripts/data/deepmoji --base_seed 5 --exp_id opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_bteo_5 --device_id 2; wait;

# Dadv model
python fairlib --dataset Moji --emb_size 2304 --num_classes 2 --num_groups 2 --batch_size 128 --lr 0.003 --dropout 0.1 --early_stopping_criterion max_balanced_dto --adv_lambda 1.0 --adv_diverse_lambda 1.0 --adv_debiasing --adv_num_subDiscriminator 3 --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --exp_id opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_dadv_1 --device_id 0&
python fairlib --dataset Moji --emb_size 2304 --num_classes 2 --num_groups 2 --batch_size 128 --lr 0.003 --dropout 0.1 --early_stopping_criterion max_balanced_dto --adv_lambda 1.0 --adv_diverse_lambda 1.0 --adv_debiasing --adv_num_subDiscriminator 3 --data_dir ../fl_scripts/data/deepmoji --base_seed 2 --exp_id opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_dadv_2 --device_id 1&
python fairlib --dataset Moji --emb_size 2304 --num_classes 2 --num_groups 2 --batch_size 128 --lr 0.003 --dropout 0.1 --early_stopping_criterion max_balanced_dto --adv_lambda 1.0 --adv_diverse_lambda 1.0 --adv_debiasing --adv_num_subDiscriminator 3 --data_dir ../fl_scripts/data/deepmoji --base_seed 3 --exp_id opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_dadv_3 --device_id 2; wait;
python fairlib --dataset Moji --emb_size 2304 --num_classes 2 --num_groups 2 --batch_size 128 --lr 0.003 --dropout 0.1 --early_stopping_criterion max_balanced_dto --adv_lambda 1.0 --adv_diverse_lambda 1.0 --adv_debiasing --adv_num_subDiscriminator 3 --data_dir ../fl_scripts/data/deepmoji --base_seed 4 --exp_id opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_dadv_4 --device_id 0&
python fairlib --dataset Moji --emb_size 2304 --num_classes 2 --num_groups 2 --batch_size 128 --lr 0.003 --dropout 0.1 --early_stopping_criterion max_balanced_dto --adv_lambda 1.0 --adv_diverse_lambda 1.0 --adv_debiasing --adv_num_subDiscriminator 3 --data_dir ../fl_scripts/data/deepmoji --base_seed 5 --exp_id opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_dadv_5 --device_id 1&

# INLP model
python fairlib --dataset Moji --emb_size 2304 --num_classes 2 --num_groups 2 --batch_size 128 --lr 0.003 --dropout 0.1 --early_stopping_criterion max_balanced_dto --INLP --INLP_min_acc 0.5 --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --exp_id opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_inlp_1 --device_id 2; wait;
python fairlib --dataset Moji --emb_size 2304 --num_classes 2 --num_groups 2 --batch_size 128 --lr 0.003 --dropout 0.1 --early_stopping_criterion max_balanced_dto --INLP --INLP_min_acc 0.5 --data_dir ../fl_scripts/data/deepmoji --base_seed 2 --exp_id opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_inlp_2 --device_id 0&
python fairlib --dataset Moji --emb_size 2304 --num_classes 2 --num_groups 2 --batch_size 128 --lr 0.003 --dropout 0.1 --early_stopping_criterion max_balanced_dto --INLP --INLP_min_acc 0.5 --data_dir ../fl_scripts/data/deepmoji --base_seed 3 --exp_id opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_inlp_3 --device_id 1&
python fairlib --dataset Moji --emb_size 2304 --num_classes 2 --num_groups 2 --batch_size 128 --lr 0.003 --dropout 0.1 --early_stopping_criterion max_balanced_dto --INLP --INLP_min_acc 0.5 --data_dir ../fl_scripts/data/deepmoji --base_seed 4 --exp_id opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_inlp_4 --device_id 2; wait;
python fairlib --dataset Moji --emb_size 2304 --num_classes 2 --num_groups 2 --batch_size 128 --lr 0.003 --dropout 0.1 --early_stopping_criterion max_balanced_dto --INLP --INLP_min_acc 0.5 --data_dir ../fl_scripts/data/deepmoji --base_seed 5 --exp_id opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_inlp_5 --device_id 0&

# FairBatch model
python fairlib --dataset Moji --emb_size 2304 --num_classes 2 --num_groups 2 --batch_size 128 --lr 0.003 --dropout 0.1 --early_stopping_criterion max_balanced_dto --DyBTalpha 0.1 --DyBT FairBatch --DyBTObj stratified_y --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --exp_id opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_fairbatch_1 --device_id 1&
python fairlib --dataset Moji --emb_size 2304 --num_classes 2 --num_groups 2 --batch_size 128 --lr 0.003 --dropout 0.1 --early_stopping_criterion max_balanced_dto --DyBTalpha 0.1 --DyBT FairBatch --DyBTObj stratified_y --data_dir ../fl_scripts/data/deepmoji --base_seed 2 --exp_id opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_fairbatch_2 --device_id 2; wait;
python fairlib --dataset Moji --emb_size 2304 --num_classes 2 --num_groups 2 --batch_size 128 --lr 0.003 --dropout 0.1 --early_stopping_criterion max_balanced_dto --DyBTalpha 0.1 --DyBT FairBatch --DyBTObj stratified_y --data_dir ../fl_scripts/data/deepmoji --base_seed 3 --exp_id opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_fairbatch_3 --device_id 0&
python fairlib --dataset Moji --emb_size 2304 --num_classes 2 --num_groups 2 --batch_size 128 --lr 0.003 --dropout 0.1 --early_stopping_criterion max_balanced_dto --DyBTalpha 0.1 --DyBT FairBatch --DyBTObj stratified_y --data_dir ../fl_scripts/data/deepmoji --base_seed 4 --exp_id opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_fairbatch_4 --device_id 1&
python fairlib --dataset Moji --emb_size 2304 --num_classes 2 --num_groups 2 --batch_size 128 --lr 0.003 --dropout 0.1 --early_stopping_criterion max_balanced_dto --DyBTalpha 0.1 --DyBT FairBatch --DyBTObj stratified_y --data_dir ../fl_scripts/data/deepmoji --base_seed 5 --exp_id opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_fairbatch_5 --device_id 2; wait;

# gd_diff model
python fairlib --dataset Moji --emb_size 2304 --num_classes 2 --num_groups 2 --batch_size 128 --lr 0.003 --dropout 0.1 --early_stopping_criterion max_balanced_dto --DyBTalpha 0.5 --DyBT GroupDifference --DyBTObj EO --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --exp_id opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_gd_diff_1 --device_id 0&
python fairlib --dataset Moji --emb_size 2304 --num_classes 2 --num_groups 2 --batch_size 128 --lr 0.003 --dropout 0.1 --early_stopping_criterion max_balanced_dto --DyBTalpha 0.5 --DyBT GroupDifference --DyBTObj EO --data_dir ../fl_scripts/data/deepmoji --base_seed 2 --exp_id opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_gd_diff_2 --device_id 1&
python fairlib --dataset Moji --emb_size 2304 --num_classes 2 --num_groups 2 --batch_size 128 --lr 0.003 --dropout 0.1 --early_stopping_criterion max_balanced_dto --DyBTalpha 0.5 --DyBT GroupDifference --DyBTObj EO --data_dir ../fl_scripts/data/deepmoji --base_seed 3 --exp_id opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_gd_diff_3 --device_id 2; wait;
python fairlib --dataset Moji --emb_size 2304 --num_classes 2 --num_groups 2 --batch_size 128 --lr 0.003 --dropout 0.1 --early_stopping_criterion max_balanced_dto --DyBTalpha 0.5 --DyBT GroupDifference --DyBTObj EO --data_dir ../fl_scripts/data/deepmoji --base_seed 4 --exp_id opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_gd_diff_4 --device_id 0&
python fairlib --dataset Moji --emb_size 2304 --num_classes 2 --num_groups 2 --batch_size 128 --lr 0.003 --dropout 0.1 --early_stopping_criterion max_balanced_dto --DyBTalpha 0.5 --DyBT GroupDifference --DyBTObj EO --data_dir ../fl_scripts/data/deepmoji --base_seed 5 --exp_id opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_gd_diff_5 --device_id 1&

# btj model
python fairlib --dataset Moji --emb_size 2304 --num_classes 2 --num_groups 2 --batch_size 128 --lr 0.003 --dropout 0.1 --early_stopping_criterion max_balanced_dto --BT Reweighting --BTObj joint --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --exp_id opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_btj_1 --device_id 2; wait;
python fairlib --dataset Moji --emb_size 2304 --num_classes 2 --num_groups 2 --batch_size 128 --lr 0.003 --dropout 0.1 --early_stopping_criterion max_balanced_dto --BT Reweighting --BTObj joint --data_dir ../fl_scripts/data/deepmoji --base_seed 2 --exp_id opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_btj_2 --device_id 0&
python fairlib --dataset Moji --emb_size 2304 --num_classes 2 --num_groups 2 --batch_size 128 --lr 0.003 --dropout 0.1 --early_stopping_criterion max_balanced_dto --BT Reweighting --BTObj joint --data_dir ../fl_scripts/data/deepmoji --base_seed 3 --exp_id opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_btj_3 --device_id 1&
python fairlib --dataset Moji --emb_size 2304 --num_classes 2 --num_groups 2 --batch_size 128 --lr 0.003 --dropout 0.1 --early_stopping_criterion max_balanced_dto --BT Reweighting --BTObj joint --data_dir ../fl_scripts/data/deepmoji --base_seed 4 --exp_id opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_btj_4 --device_id 2; wait;
python fairlib --dataset Moji --emb_size 2304 --num_classes 2 --num_groups 2 --batch_size 128 --lr 0.003 --dropout 0.1 --early_stopping_criterion max_balanced_dto --BT Reweighting --BTObj joint --data_dir ../fl_scripts/data/deepmoji --base_seed 5 --exp_id opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_btj_5 --device_id 0; wait;






cd ../uncertainty-estimation/src
# MC part
# calc UE

HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[0,1,2] seeds=[1,2,3,4,5] script=run_glue.py args='ue\=mc ue.dropout_subs\=all ue.use_selective\=False ue.reg_type\=raw do_ue_estimate\=True ue.use_cache\=False ue.calibrate\=False data.validation_subsample\=0.0 training\=electra_base model.model_name_or_path\=fairlib_mlp fairlib.num_classes\=2 fairlib.emb_size\=2304 ++data.validation_name\=test cache_dir\=../../fl_scripts/data fairlib.dropout\=0.1' config_path=../configs/moji_preproc.yaml output_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_vanilla/moji_preproc/mc model_series_dir=../../fairlib_uncertainty/results/dev/Moji/opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_vanilla
# calc UE metrics
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_vanilla/moji_preproc/mc extract_config=False output_dir=../workdir/run_calc_ues_metrics_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_vanilla/moji_preproc/mc;


HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[0,1,2] seeds=[1,2,3,4,5] script=run_glue.py args='ue\=mc ue.dropout_subs\=all ue.use_selective\=False ue.reg_type\=raw do_ue_estimate\=True ue.use_cache\=False ue.calibrate\=False data.validation_subsample\=0.0 training\=electra_base model.model_name_or_path\=fairlib_mlp fairlib.num_classes\=2 fairlib.emb_size\=2304 ++data.validation_name\=test cache_dir\=../../fl_scripts/data fairlib.dropout\=0.1 fairlib.adv_debiasing\=True' config_path=../configs/moji_preproc.yaml output_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_adv/moji_preproc/mc model_series_dir=../../fairlib_uncertainty/results/dev/Moji/opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_adv
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_adv/moji_preproc/mc extract_config=False output_dir=../workdir/run_calc_ues_metrics_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_adv/moji_preproc/mc;


HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[0,1,2] seeds=[1,2,3,4,5] script=run_glue.py args='ue\=mc ue.dropout_subs\=all ue.use_selective\=False ue.reg_type\=raw do_ue_estimate\=True ue.use_cache\=False ue.calibrate\=False data.validation_subsample\=0.0 training\=electra_base model.model_name_or_path\=fairlib_mlp fairlib.num_classes\=2 fairlib.emb_size\=2304 ++data.validation_name\=test cache_dir\=../../fl_scripts/data fairlib.dropout\=0.1' config_path=../configs/moji_preproc.yaml output_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_bteo/moji_preproc/mc model_series_dir=../../fairlib_uncertainty/results/dev/Moji/opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_bteo
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_bteo/moji_preproc/mc extract_config=False output_dir=../workdir/run_calc_ues_metrics_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_bteo/moji_preproc/mc;


HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[0,1,2] seeds=[1,2,3,4,5] script=run_glue.py args='ue\=mc ue.dropout_subs\=all ue.use_selective\=False ue.reg_type\=raw do_ue_estimate\=True ue.use_cache\=False ue.calibrate\=False data.validation_subsample\=0.0 training\=electra_base model.model_name_or_path\=fairlib_mlp fairlib.num_classes\=2 fairlib.emb_size\=2304 ++data.validation_name\=test cache_dir\=../../fl_scripts/data fairlib.dropout\=0.1 fairlib.adv_debiasing\=True' config_path=../configs/moji_preproc.yaml output_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_dadv/moji_preproc/mc model_series_dir=../../fairlib_uncertainty/results/dev/Moji/opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_dadv
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_dadv/moji_preproc/mc extract_config=False output_dir=../workdir/run_calc_ues_metrics_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_dadv/moji_preproc/mc;


HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[0,1,2] seeds=[1,2,3,4,5] script=run_glue.py args='ue\=mc ue.dropout_subs\=all ue.use_selective\=False ue.reg_type\=raw do_ue_estimate\=True ue.use_cache\=False ue.calibrate\=False data.validation_subsample\=0.0 training\=electra_base model.model_name_or_path\=fairlib_mlp fairlib.num_classes\=2 fairlib.emb_size\=2304 ++data.validation_name\=test cache_dir\=../../fl_scripts/data fairlib.dropout\=0.1 fairlib.INLP\=True +fairlib.INLP_checkpoint\=INLP_bdto_checkpoint_epoch_cls_BEST.pth.tar' config_path=../configs/moji_preproc.yaml output_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_inlp/moji_preproc/mc model_series_dir=../../fairlib_uncertainty/results/dev/Moji/opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_inlp
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_inlp/moji_preproc/mc extract_config=False output_dir=../workdir/run_calc_ues_metrics_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_inlp/moji_preproc/mc;

HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[0,1,2] seeds=[1,2,3,4,5] script=run_glue.py args='ue\=mc ue.dropout_subs\=all ue.use_selective\=False ue.reg_type\=raw do_ue_estimate\=True ue.use_cache\=False ue.calibrate\=False data.validation_subsample\=0.0 training\=electra_base model.model_name_or_path\=fairlib_mlp fairlib.num_classes\=2 fairlib.emb_size\=2304 ++data.validation_name\=test cache_dir\=../../fl_scripts/data fairlib.dropout\=0.1' config_path=../configs/moji_preproc.yaml output_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_fairbatch/moji_preproc/mc model_series_dir=../../fairlib_uncertainty/results/dev/Moji/opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_fairbatch
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_fairbatch/moji_preproc/mc extract_config=False output_dir=../workdir/run_calc_ues_metrics_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_fairbatch/moji_preproc/mc;


HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[0,1,2] seeds=[1,2,3,4,5] script=run_glue.py args='ue\=mc ue.dropout_subs\=all ue.use_selective\=False ue.reg_type\=raw do_ue_estimate\=True ue.use_cache\=False ue.calibrate\=False data.validation_subsample\=0.0 training\=electra_base model.model_name_or_path\=fairlib_mlp fairlib.num_classes\=2 fairlib.emb_size\=2304 ++data.validation_name\=test cache_dir\=../../fl_scripts/data fairlib.dropout\=0.1' config_path=../configs/moji_preproc.yaml output_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_gd_diff/moji_preproc/mc model_series_dir=../../fairlib_uncertainty/results/dev/Moji/opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_gd_diff
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_gd_diff/moji_preproc/mc extract_config=False output_dir=../workdir/run_calc_ues_metrics_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_gd_diff/moji_preproc/mc;

HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[0,1,2] seeds=[1,2,3,4,5] script=run_glue.py args='ue\=mc ue.dropout_subs\=all ue.use_selective\=False ue.reg_type\=raw do_ue_estimate\=True ue.use_cache\=False ue.calibrate\=False data.validation_subsample\=0.0 training\=electra_base model.model_name_or_path\=fairlib_mlp fairlib.num_classes\=2 fairlib.emb_size\=2304 ++data.validation_name\=test cache_dir\=../../fl_scripts/data fairlib.dropout\=0.1' config_path=../configs/moji_preproc.yaml output_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_btj/moji_preproc/mc model_series_dir=../../fairlib_uncertainty/results/dev/Moji/opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_btj
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_btj/moji_preproc/mc extract_config=False output_dir=../workdir/run_calc_ues_metrics_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_btj/moji_preproc/mc;





# mahalanobis
HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[0,1,2] seeds=[1,2,3,4,5] script=run_glue.py args='ue\=mahalanobis ue.use_selective\=False ue.reg_type\=raw do_ue_estimate\=True ue.use_cache\=False ue.calibrate\=False data.validation_subsample\=0.0 training\=electra_base model.model_name_or_path\=fairlib_mlp fairlib.num_classes\=2 fairlib.emb_size\=2304 ++data.validation_name\=test cache_dir\=../../fl_scripts/data fairlib.dropout\=0.1' config_path=../configs/moji_preproc.yaml output_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_vanilla/moji_preproc/mahalanobis model_series_dir=../../fairlib_uncertainty/results/dev/Moji/opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_vanilla
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_vanilla/moji_preproc/mahalanobis extract_config=False output_dir=../workdir/run_calc_ues_metrics_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_vanilla/moji_preproc/mahalanobis;


HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[0,1,2] seeds=[1,2,3,4,5] script=run_glue.py args='ue\=mahalanobis ue.use_selective\=False ue.reg_type\=raw do_ue_estimate\=True ue.use_cache\=False ue.calibrate\=False data.validation_subsample\=0.0 training\=electra_base model.model_name_or_path\=fairlib_mlp fairlib.num_classes\=2 fairlib.emb_size\=2304 ++data.validation_name\=test cache_dir\=../../fl_scripts/data fairlib.dropout\=0.1 fairlib.adv_debiasing\=True' config_path=../configs/moji_preproc.yaml output_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_adv/moji_preproc/mahalanobis model_series_dir=../../fairlib_uncertainty/results/dev/Moji/opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_adv
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_adv/moji_preproc/mahalanobis extract_config=False output_dir=../workdir/run_calc_ues_metrics_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_adv/moji_preproc/mahalanobis;


HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[0,1,2] seeds=[1,2,3,4,5] script=run_glue.py args='ue\=mahalanobis ue.use_selective\=False ue.reg_type\=raw do_ue_estimate\=True ue.use_cache\=False ue.calibrate\=False data.validation_subsample\=0.0 training\=electra_base model.model_name_or_path\=fairlib_mlp fairlib.num_classes\=2 fairlib.emb_size\=2304 ++data.validation_name\=test cache_dir\=../../fl_scripts/data fairlib.dropout\=0.1' config_path=../configs/moji_preproc.yaml output_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_bteo/moji_preproc/mahalanobis model_series_dir=../../fairlib_uncertainty/results/dev/Moji/opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_bteo
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_bteo/moji_preproc/mahalanobis extract_config=False output_dir=../workdir/run_calc_ues_metrics_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_bteo/moji_preproc/mahalanobis;


HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[0,1,2] seeds=[1,2,3,4,5] script=run_glue.py args='ue\=mahalanobis ue.use_selective\=False ue.reg_type\=raw do_ue_estimate\=True ue.use_cache\=False ue.calibrate\=False data.validation_subsample\=0.0 training\=electra_base model.model_name_or_path\=fairlib_mlp fairlib.num_classes\=2 fairlib.emb_size\=2304 ++data.validation_name\=test cache_dir\=../../fl_scripts/data fairlib.dropout\=0.1 fairlib.adv_debiasing\=True' config_path=../configs/moji_preproc.yaml output_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_dadv/moji_preproc/mahalanobis model_series_dir=../../fairlib_uncertainty/results/dev/Moji/opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_dadv
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_dadv/moji_preproc/mahalanobis extract_config=False output_dir=../workdir/run_calc_ues_metrics_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_dadv/moji_preproc/mahalanobis;

HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[0,1,2] seeds=[1,2,3,4,5] script=run_glue.py args='ue\=mahalanobis ue.use_selective\=False ue.reg_type\=raw do_ue_estimate\=True ue.use_cache\=False ue.calibrate\=False data.validation_subsample\=0.0 training\=electra_base model.model_name_or_path\=fairlib_mlp fairlib.num_classes\=2 fairlib.emb_size\=2304 ++data.validation_name\=test cache_dir\=../../fl_scripts/data fairlib.dropout\=0.1 fairlib.INLP\=True +fairlib.INLP_checkpoint\=INLP_bdto_checkpoint_epoch_cls_BEST.pth.tar' config_path=../configs/moji_preproc.yaml output_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_inlp/moji_preproc/mahalanobis model_series_dir=../../fairlib_uncertainty/results/dev/Moji/opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_inlp
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_inlp/moji_preproc/mahalanobis extract_config=False output_dir=../workdir/run_calc_ues_metrics_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_inlp/moji_preproc/mahalanobis;



HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[0,1,2] seeds=[1,2,3,4,5] script=run_glue.py args='ue\=mahalanobis ue.use_selective\=False ue.reg_type\=raw do_ue_estimate\=True ue.use_cache\=False ue.calibrate\=False data.validation_subsample\=0.0 training\=electra_base model.model_name_or_path\=fairlib_mlp fairlib.num_classes\=2 fairlib.emb_size\=2304 ++data.validation_name\=test cache_dir\=../../fl_scripts/data fairlib.dropout\=0.1' config_path=../configs/moji_preproc.yaml output_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_fairbatch/moji_preproc/mahalanobis model_series_dir=../../fairlib_uncertainty/results/dev/Moji/opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_fairbatch
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_fairbatch/moji_preproc/mahalanobis extract_config=False output_dir=../workdir/run_calc_ues_metrics_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_fairbatch/moji_preproc/mahalanobis;


HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[0,1,2] seeds=[1,2,3,4,5] script=run_glue.py args='ue\=mahalanobis ue.use_selective\=False ue.reg_type\=raw do_ue_estimate\=True ue.use_cache\=False ue.calibrate\=False data.validation_subsample\=0.0 training\=electra_base model.model_name_or_path\=fairlib_mlp fairlib.num_classes\=2 fairlib.emb_size\=2304 ++data.validation_name\=test cache_dir\=../../fl_scripts/data fairlib.dropout\=0.1' config_path=../configs/moji_preproc.yaml output_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_gd_diff/moji_preproc/mahalanobis model_series_dir=../../fairlib_uncertainty/results/dev/Moji/opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_gd_diff
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_gd_diff/moji_preproc/mahalanobis extract_config=False output_dir=../workdir/run_calc_ues_metrics_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_gd_diff/moji_preproc/mahalanobis;

HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[0,1,2] seeds=[1,2,3,4,5] script=run_glue.py args='ue\=mahalanobis ue.use_selective\=False ue.reg_type\=raw do_ue_estimate\=True ue.use_cache\=False ue.calibrate\=False data.validation_subsample\=0.0 training\=electra_base model.model_name_or_path\=fairlib_mlp fairlib.num_classes\=2 fairlib.emb_size\=2304 ++data.validation_name\=test cache_dir\=../../fl_scripts/data fairlib.dropout\=0.1' config_path=../configs/moji_preproc.yaml output_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_btj/moji_preproc/mahalanobis model_series_dir=../../fairlib_uncertainty/results/dev/Moji/opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_btj
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_btj/moji_preproc/mahalanobis extract_config=False output_dir=../workdir/run_calc_ues_metrics_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_btj/moji_preproc/mahalanobis;


# DDU
HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[0,1,2] seeds=[1,2,3,4,5] script=run_glue.py args='ue\=ddu ue.use_selective\=False ue.reg_type\=raw do_ue_estimate\=True ue.use_cache\=False ue.calibrate\=False data.validation_subsample\=0.0 training\=electra_base model.model_name_or_path\=fairlib_mlp fairlib.num_classes\=2 fairlib.emb_size\=2304 ++data.validation_name\=test cache_dir\=../../fl_scripts/data fairlib.dropout\=0.1' config_path=../configs/moji_preproc.yaml output_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_vanilla/moji_preproc/ddu model_series_dir=../../fairlib_uncertainty/results/dev/Moji/opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_vanilla
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_vanilla/moji_preproc/ddu extract_config=False output_dir=../workdir/run_calc_ues_metrics_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_vanilla/moji_preproc/ddu;


HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[0,1,2] seeds=[1,2,3,4,5] script=run_glue.py args='ue\=ddu ue.use_selective\=False ue.reg_type\=raw do_ue_estimate\=True ue.use_cache\=False ue.calibrate\=False data.validation_subsample\=0.0 training\=electra_base model.model_name_or_path\=fairlib_mlp fairlib.num_classes\=2 fairlib.emb_size\=2304 ++data.validation_name\=test cache_dir\=../../fl_scripts/data fairlib.dropout\=0.1 fairlib.adv_debiasing\=True' config_path=../configs/moji_preproc.yaml output_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_adv/moji_preproc/ddu model_series_dir=../../fairlib_uncertainty/results/dev/Moji/opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_adv
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_adv/moji_preproc/ddu extract_config=False output_dir=../workdir/run_calc_ues_metrics_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_adv/moji_preproc/ddu;


HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[0,1,2] seeds=[1,2,3,4,5] script=run_glue.py args='ue\=ddu ue.use_selective\=False ue.reg_type\=raw do_ue_estimate\=True ue.use_cache\=False ue.calibrate\=False data.validation_subsample\=0.0 training\=electra_base model.model_name_or_path\=fairlib_mlp fairlib.num_classes\=2 fairlib.emb_size\=2304 ++data.validation_name\=test cache_dir\=../../fl_scripts/data fairlib.dropout\=0.1' config_path=../configs/moji_preproc.yaml output_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_bteo/moji_preproc/ddu model_series_dir=../../fairlib_uncertainty/results/dev/Moji/opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_bteo
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_bteo/moji_preproc/ddu extract_config=False output_dir=../workdir/run_calc_ues_metrics_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_bteo/moji_preproc/ddu;


HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[0,1,2] seeds=[1,2,3,4,5] script=run_glue.py args='ue\=ddu ue.use_selective\=False ue.reg_type\=raw do_ue_estimate\=True ue.use_cache\=False ue.calibrate\=False data.validation_subsample\=0.0 training\=electra_base model.model_name_or_path\=fairlib_mlp fairlib.num_classes\=2 fairlib.emb_size\=2304 ++data.validation_name\=test cache_dir\=../../fl_scripts/data fairlib.dropout\=0.1 fairlib.adv_debiasing\=True' config_path=../configs/moji_preproc.yaml output_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_dadv/moji_preproc/ddu model_series_dir=../../fairlib_uncertainty/results/dev/Moji/opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_dadv
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_dadv/moji_preproc/ddu extract_config=False output_dir=../workdir/run_calc_ues_metrics_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_dadv/moji_preproc/ddu;

HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[0,1,2] seeds=[1,2,3,4,5] script=run_glue.py args='ue\=ddu ue.use_selective\=False ue.reg_type\=raw do_ue_estimate\=True ue.use_cache\=False ue.calibrate\=False data.validation_subsample\=0.0 training\=electra_base model.model_name_or_path\=fairlib_mlp fairlib.num_classes\=2 fairlib.emb_size\=2304 ++data.validation_name\=test cache_dir\=../../fl_scripts/data fairlib.dropout\=0.1 fairlib.INLP\=True +fairlib.INLP_checkpoint\=INLP_bdto_checkpoint_epoch_cls_BEST.pth.tar' config_path=../configs/moji_preproc.yaml output_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_inlp/moji_preproc/ddu model_series_dir=../../fairlib_uncertainty/results/dev/Moji/opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_inlp
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_inlp/moji_preproc/ddu extract_config=False output_dir=../workdir/run_calc_ues_metrics_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_inlp/moji_preproc/ddu;


HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[0,1,2] seeds=[1,2,3,4,5] script=run_glue.py args='ue\=ddu ue.use_selective\=False ue.reg_type\=raw do_ue_estimate\=True ue.use_cache\=False ue.calibrate\=False data.validation_subsample\=0.0 training\=electra_base model.model_name_or_path\=fairlib_mlp fairlib.num_classes\=2 fairlib.emb_size\=2304 ++data.validation_name\=test cache_dir\=../../fl_scripts/data fairlib.dropout\=0.1' config_path=../configs/moji_preproc.yaml output_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_fairbatch/moji_preproc/ddu model_series_dir=../../fairlib_uncertainty/results/dev/Moji/opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_fairbatch
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_fairbatch/moji_preproc/ddu extract_config=False output_dir=../workdir/run_calc_ues_metrics_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_fairbatch/moji_preproc/ddu;


HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[0,1,2] seeds=[1,2,3,4,5] script=run_glue.py args='ue\=ddu ue.use_selective\=False ue.reg_type\=raw do_ue_estimate\=True ue.use_cache\=False ue.calibrate\=False data.validation_subsample\=0.0 training\=electra_base model.model_name_or_path\=fairlib_mlp fairlib.num_classes\=2 fairlib.emb_size\=2304 ++data.validation_name\=test cache_dir\=../../fl_scripts/data fairlib.dropout\=0.1' config_path=../configs/moji_preproc.yaml output_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_gd_diff/moji_preproc/ddu model_series_dir=../../fairlib_uncertainty/results/dev/Moji/opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_gd_diff
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_gd_diff/moji_preproc/ddu extract_config=False output_dir=../workdir/run_calc_ues_metrics_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_gd_diff/moji_preproc/ddu;


HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[0,1,2] seeds=[1,2,3,4,5] script=run_glue.py args='ue\=ddu ue.use_selective\=False ue.reg_type\=raw do_ue_estimate\=True ue.use_cache\=False ue.calibrate\=False data.validation_subsample\=0.0 training\=electra_base model.model_name_or_path\=fairlib_mlp fairlib.num_classes\=2 fairlib.emb_size\=2304 ++data.validation_name\=test cache_dir\=../../fl_scripts/data fairlib.dropout\=0.1' config_path=../configs/moji_preproc.yaml output_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_btj/moji_preproc/ddu model_series_dir=../../fairlib_uncertainty/results/dev/Moji/opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_btj
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_btj/moji_preproc/ddu extract_config=False output_dir=../workdir/run_calc_ues_metrics_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_btj/moji_preproc/ddu;


# deep_fool
HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[0,1,2] seeds=[1,2,3,4,5] script=run_glue.py args='ue\=deep_fool ue.use_selective\=False ue.reg_type\=raw do_ue_estimate\=True ue.use_cache\=False ue.calibrate\=False data.validation_subsample\=0.0 training\=electra_base model.model_name_or_path\=fairlib_mlp fairlib.num_classes\=2 fairlib.emb_size\=2304 ++data.validation_name\=test cache_dir\=../../fl_scripts/data fairlib.dropout\=0.1' config_path=../configs/moji_preproc.yaml output_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_vanilla/moji_preproc/deep_fool model_series_dir=../../fairlib_uncertainty/results/dev/Moji/opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_vanilla
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_vanilla/moji_preproc/deep_fool extract_config=False output_dir=../workdir/run_calc_ues_metrics_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_vanilla/moji_preproc/deep_fool;


HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[0,1,2] seeds=[1,2,3,4,5] script=run_glue.py args='ue\=deep_fool ue.use_selective\=False ue.reg_type\=raw do_ue_estimate\=True ue.use_cache\=False ue.calibrate\=False data.validation_subsample\=0.0 training\=electra_base model.model_name_or_path\=fairlib_mlp fairlib.num_classes\=2 fairlib.emb_size\=2304 ++data.validation_name\=test cache_dir\=../../fl_scripts/data fairlib.dropout\=0.1 fairlib.adv_debiasing\=True' config_path=../configs/moji_preproc.yaml output_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_adv/moji_preproc/deep_fool model_series_dir=../../fairlib_uncertainty/results/dev/Moji/opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_adv
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_adv/moji_preproc/deep_fool extract_config=False output_dir=../workdir/run_calc_ues_metrics_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_adv/moji_preproc/deep_fool;


HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[0,1,2] seeds=[1,2,3,4,5] script=run_glue.py args='ue\=deep_fool ue.use_selective\=False ue.reg_type\=raw do_ue_estimate\=True ue.use_cache\=False ue.calibrate\=False data.validation_subsample\=0.0 training\=electra_base model.model_name_or_path\=fairlib_mlp fairlib.num_classes\=2 fairlib.emb_size\=2304 ++data.validation_name\=test cache_dir\=../../fl_scripts/data fairlib.dropout\=0.1' config_path=../configs/moji_preproc.yaml output_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_bteo/moji_preproc/deep_fool model_series_dir=../../fairlib_uncertainty/results/dev/Moji/opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_bteo
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_bteo/moji_preproc/deep_fool extract_config=False output_dir=../workdir/run_calc_ues_metrics_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_bteo/moji_preproc/deep_fool;


HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[0,1,2] seeds=[1,2,3,4,5] script=run_glue.py args='ue\=deep_fool ue.use_selective\=False ue.reg_type\=raw do_ue_estimate\=True ue.use_cache\=False ue.calibrate\=False data.validation_subsample\=0.0 training\=electra_base model.model_name_or_path\=fairlib_mlp fairlib.num_classes\=2 fairlib.emb_size\=2304 ++data.validation_name\=test cache_dir\=../../fl_scripts/data fairlib.dropout\=0.1 fairlib.adv_debiasing\=True' config_path=../configs/moji_preproc.yaml output_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_dadv/moji_preproc/deep_fool model_series_dir=../../fairlib_uncertainty/results/dev/Moji/opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_dadv
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_dadv/moji_preproc/deep_fool extract_config=False output_dir=../workdir/run_calc_ues_metrics_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_dadv/moji_preproc/deep_fool;

HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[0,1,2] seeds=[1,2,3,4,5] script=run_glue.py args='ue\=deep_fool ue.use_selective\=False ue.reg_type\=raw do_ue_estimate\=True ue.use_cache\=False ue.calibrate\=False data.validation_subsample\=0.0 training\=electra_base model.model_name_or_path\=fairlib_mlp fairlib.num_classes\=2 fairlib.emb_size\=2304 ++data.validation_name\=test cache_dir\=../../fl_scripts/data fairlib.dropout\=0.1 fairlib.INLP\=True +fairlib.INLP_checkpoint\=INLP_bdto_checkpoint_epoch_cls_BEST.pth.tar' config_path=../configs/moji_preproc.yaml output_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_inlp/moji_preproc/deep_fool model_series_dir=../../fairlib_uncertainty/results/dev/Moji/opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_inlp
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_inlp/moji_preproc/deep_fool extract_config=False output_dir=../workdir/run_calc_ues_metrics_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_inlp/moji_preproc/deep_fool;


HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[0,1,2] seeds=[1,2,3,4,5] script=run_glue.py args='ue\=deep_fool ue.use_selective\=False ue.reg_type\=raw do_ue_estimate\=True ue.use_cache\=False ue.calibrate\=False data.validation_subsample\=0.0 training\=electra_base model.model_name_or_path\=fairlib_mlp fairlib.num_classes\=2 fairlib.emb_size\=2304 ++data.validation_name\=test cache_dir\=../../fl_scripts/data fairlib.dropout\=0.1' config_path=../configs/moji_preproc.yaml output_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_fairbatch/moji_preproc/deep_fool model_series_dir=../../fairlib_uncertainty/results/dev/Moji/opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_fairbatch
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_fairbatch/moji_preproc/deep_fool extract_config=False output_dir=../workdir/run_calc_ues_metrics_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_fairbatch/moji_preproc/deep_fool;


HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[0,1,2] seeds=[1,2,3,4,5] script=run_glue.py args='ue\=deep_fool ue.use_selective\=False ue.reg_type\=raw do_ue_estimate\=True ue.use_cache\=False ue.calibrate\=False data.validation_subsample\=0.0 training\=electra_base model.model_name_or_path\=fairlib_mlp fairlib.num_classes\=2 fairlib.emb_size\=2304 ++data.validation_name\=test cache_dir\=../../fl_scripts/data fairlib.dropout\=0.1' config_path=../configs/moji_preproc.yaml output_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_gd_diff/moji_preproc/deep_fool model_series_dir=../../fairlib_uncertainty/results/dev/Moji/opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_gd_diff
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_gd_diff/moji_preproc/deep_fool extract_config=False output_dir=../workdir/run_calc_ues_metrics_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_gd_diff/moji_preproc/deep_fool;

HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[0,1,2] seeds=[1,2,3,4,5] script=run_glue.py args='ue\=deep_fool ue.use_selective\=False ue.reg_type\=raw do_ue_estimate\=True ue.use_cache\=False ue.calibrate\=False data.validation_subsample\=0.0 training\=electra_base model.model_name_or_path\=fairlib_mlp fairlib.num_classes\=2 fairlib.emb_size\=2304 ++data.validation_name\=test cache_dir\=../../fl_scripts/data fairlib.dropout\=0.1' config_path=../configs/moji_preproc.yaml output_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_btj/moji_preproc/deep_fool model_series_dir=../../fairlib_uncertainty/results/dev/Moji/opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_btj
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir=../workdir/run_tasks_for_model_series_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_btj/moji_preproc/deep_fool extract_config=False output_dir=../workdir/run_calc_ues_metrics_fix_test_data_opt_mdto_deb_moji_bal/fairlib_mlp_moji_btj/moji_preproc/deep_fool;




# Now run MD on validation for HUE
# mahalanobis
HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[0,1,2] seeds=[1,2,3,4,5] script=run_glue.py args='ue\=mahalanobis ue.use_selective\=False ue.reg_type\=raw do_ue_estimate\=True ue.use_cache\=False ue.calibrate\=False data.validation_subsample\=0.0 training\=electra_base model.model_name_or_path\=fairlib_mlp data.validation_name\=validation fairlib.num_classes\=2 fairlib.emb_size\=2304 ++data.validation_name\=test cache_dir\=../../fl_scripts/data fairlib.dropout\=0.1' config_path=../configs/moji_preproc.yaml output_dir=../workdir/run_tasks_for_model_series_fix_val_data_opt_bdto_deb/fairlib_mlp_moji_vanilla/moji_preproc/mahalanobis model_series_dir=../../fairlib_uncertainty/results/dev/Moji/opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_vanilla
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir=../workdir/run_tasks_for_model_series_fix_val_data_opt_bdto_deb/fairlib_mlp_moji_vanilla/moji_preproc/mahalanobis extract_config=False output_dir=../workdir/run_calc_ues_metrics_fix_val_data_opt_bdto_deb/fairlib_mlp_moji_vanilla/moji_preproc/mahalanobis;


HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[0,1,2] seeds=[1,2,3,4,5] script=run_glue.py args='ue\=mahalanobis ue.use_selective\=False ue.reg_type\=raw do_ue_estimate\=True ue.use_cache\=False ue.calibrate\=False data.validation_subsample\=0.0 training\=electra_base model.model_name_or_path\=fairlib_mlp data.validation_name\=validation fairlib.num_classes\=2 fairlib.emb_size\=2304 ++data.validation_name\=test cache_dir\=../../fl_scripts/data fairlib.dropout\=0.1 fairlib.adv_debiasing\=True' config_path=../configs/moji_preproc.yaml output_dir=../workdir/run_tasks_for_model_series_fix_val_data_opt_bdto_deb/fairlib_mlp_moji_adv/moji_preproc/mahalanobis model_series_dir=../../fairlib_uncertainty/results/dev/Moji/opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_adv
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir=../workdir/run_tasks_for_model_series_fix_val_data_opt_bdto_deb/fairlib_mlp_moji_adv/moji_preproc/mahalanobis extract_config=False output_dir=../workdir/run_calc_ues_metrics_fix_val_data_opt_bdto_deb/fairlib_mlp_moji_adv/moji_preproc/mahalanobis;


HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[0,1,2] seeds=[1,2,3,4,5] script=run_glue.py args='ue\=mahalanobis ue.use_selective\=False ue.reg_type\=raw do_ue_estimate\=True ue.use_cache\=False ue.calibrate\=False data.validation_subsample\=0.0 training\=electra_base model.model_name_or_path\=fairlib_mlp data.validation_name\=validation fairlib.num_classes\=2 fairlib.emb_size\=2304 ++data.validation_name\=test cache_dir\=../../fl_scripts/data fairlib.dropout\=0.1' config_path=../configs/moji_preproc.yaml output_dir=../workdir/run_tasks_for_model_series_fix_val_data_opt_bdto_deb/fairlib_mlp_moji_bteo/moji_preproc/mahalanobis model_series_dir=../../fairlib_uncertainty/results/dev/Moji/opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_bteo
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir=../workdir/run_tasks_for_model_series_fix_val_data_opt_bdto_deb/fairlib_mlp_moji_bteo/moji_preproc/mahalanobis extract_config=False output_dir=../workdir/run_calc_ues_metrics_fix_val_data_opt_bdto_deb/fairlib_mlp_moji_bteo/moji_preproc/mahalanobis;


HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[0,1,2] seeds=[1,2,3,4,5] script=run_glue.py args='ue\=mahalanobis ue.use_selective\=False ue.reg_type\=raw do_ue_estimate\=True ue.use_cache\=False ue.calibrate\=False data.validation_subsample\=0.0 training\=electra_base model.model_name_or_path\=fairlib_mlp data.validation_name\=validation fairlib.num_classes\=2 fairlib.emb_size\=2304 ++data.validation_name\=test cache_dir\=../../fl_scripts/data fairlib.dropout\=0.1 fairlib.adv_debiasing\=True' config_path=../configs/moji_preproc.yaml output_dir=../workdir/run_tasks_for_model_series_fix_val_data_opt_bdto_deb/fairlib_mlp_moji_dadv/moji_preproc/mahalanobis model_series_dir=../../fairlib_uncertainty/results/dev/Moji/opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_dadv
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir=../workdir/run_tasks_for_model_series_fix_val_data_opt_bdto_deb/fairlib_mlp_moji_dadv/moji_preproc/mahalanobis extract_config=False output_dir=../workdir/run_calc_ues_metrics_fix_val_data_opt_bdto_deb/fairlib_mlp_moji_dadv/moji_preproc/mahalanobis;

HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[0,1,2] seeds=[1,2,3,4,5] script=run_glue.py args='ue\=mahalanobis ue.use_selective\=False ue.reg_type\=raw do_ue_estimate\=True ue.use_cache\=False ue.calibrate\=False data.validation_subsample\=0.0 training\=electra_base model.model_name_or_path\=fairlib_mlp data.validation_name\=validation fairlib.num_classes\=2 fairlib.emb_size\=2304 ++data.validation_name\=test cache_dir\=../../fl_scripts/data fairlib.dropout\=0.1 fairlib.INLP\=True +fairlib.INLP_checkpoint\=INLP_bdto_checkpoint_epoch_cls_BEST.pth.tar' config_path=../configs/moji_preproc.yaml output_dir=../workdir/run_tasks_for_model_series_fix_val_data_opt_bdto_deb/fairlib_mlp_moji_inlp/moji_preproc/mahalanobis model_series_dir=../../fairlib_uncertainty/results/dev/Moji/opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_inlp
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir=../workdir/run_tasks_for_model_series_fix_val_data_opt_bdto_deb/fairlib_mlp_moji_inlp/moji_preproc/mahalanobis extract_config=False output_dir=../workdir/run_calc_ues_metrics_fix_val_data_opt_bdto_deb/fairlib_mlp_moji_inlp/moji_preproc/mahalanobis;

HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[0,1,2] seeds=[1,2,3,4,5] script=run_glue.py args='ue\=mahalanobis ue.use_selective\=False ue.reg_type\=raw do_ue_estimate\=True ue.use_cache\=False ue.calibrate\=False data.validation_subsample\=0.0 training\=electra_base model.model_name_or_path\=fairlib_mlp data.validation_name\=validation fairlib.num_classes\=2 fairlib.emb_size\=2304 ++data.validation_name\=test cache_dir\=../../fl_scripts/data fairlib.dropout\=0.1' config_path=../configs/moji_preproc.yaml output_dir=../workdir/run_tasks_for_model_series_fix_val_data_opt_bdto_deb/fairlib_mlp_moji_fairbatch/moji_preproc/mahalanobis model_series_dir=../../fairlib_uncertainty/results/dev/Moji/opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_fairbatch
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir=../workdir/run_tasks_for_model_series_fix_val_data_opt_bdto_deb/fairlib_mlp_moji_fairbatch/moji_preproc/mahalanobis extract_config=False output_dir=../workdir/run_calc_ues_metrics_fix_val_data_opt_bdto_deb/fairlib_mlp_moji_fairbatch/moji_preproc/mahalanobis;


HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[0,1,2] seeds=[1,2,3,4,5] script=run_glue.py args='ue\=mahalanobis ue.use_selective\=False ue.reg_type\=raw do_ue_estimate\=True ue.use_cache\=False ue.calibrate\=False data.validation_subsample\=0.0 training\=electra_base model.model_name_or_path\=fairlib_mlp data.validation_name\=validation fairlib.num_classes\=2 fairlib.emb_size\=2304 ++data.validation_name\=test cache_dir\=../../fl_scripts/data fairlib.dropout\=0.1' config_path=../configs/moji_preproc.yaml output_dir=../workdir/run_tasks_for_model_series_fix_val_data_opt_bdto_deb/fairlib_mlp_moji_gd_diff/moji_preproc/mahalanobis model_series_dir=../../fairlib_uncertainty/results/dev/Moji/opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_gd_diff
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir=../workdir/run_tasks_for_model_series_fix_val_data_opt_bdto_deb/fairlib_mlp_moji_gd_diff/moji_preproc/mahalanobis extract_config=False output_dir=../workdir/run_calc_ues_metrics_fix_val_data_opt_bdto_deb/fairlib_mlp_moji_gd_diff/moji_preproc/mahalanobis;


HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[0,1,2] seeds=[1,2,3,4,5] script=run_glue.py args='ue\=mahalanobis ue.use_selective\=False ue.reg_type\=raw do_ue_estimate\=True ue.use_cache\=False ue.calibrate\=False data.validation_subsample\=0.0 training\=electra_base model.model_name_or_path\=fairlib_mlp data.validation_name\=validation fairlib.num_classes\=2 fairlib.emb_size\=2304 ++data.validation_name\=test cache_dir\=../../fl_scripts/data fairlib.dropout\=0.1' config_path=../configs/moji_preproc.yaml output_dir=../workdir/run_tasks_for_model_series_fix_val_data_opt_bdto_deb/fairlib_mlp_moji_btj/moji_preproc/mahalanobis model_series_dir=../../fairlib_uncertainty/results/dev/Moji/opt_mlp_moji_bal_mdto/moji_fairlib_mlp_opt_mdto_deb_btj
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir=../workdir/run_tasks_for_model_series_fix_val_data_opt_bdto_deb/fairlib_mlp_moji_btj/moji_preproc/mahalanobis extract_config=False output_dir=../workdir/run_calc_ues_metrics_fix_val_data_opt_bdto_deb/fairlib_mlp_moji_btj/moji_preproc/mahalanobis;
