cd ../

python fairlib --dataset Moji --emb_size 768 --num_classes 2 --encoder_architecture BERT --batch_size 16 --test_batch_size 32 --dropout 0.1 --weight_decay 0 --lr 1e-06 --epochs 20 --epochs_since_improvement 5 --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --model_name "vinai/bertweet-base" --exp_id hp_search_moji_bertweet_bal/fairlib_bert_moji_vanilla_1/5_16_1e-06_0 --device_id 0&
python fairlib --dataset Moji --emb_size 768 --num_classes 2 --encoder_architecture BERT --batch_size 16 --test_batch_size 32 --dropout 0.1 --weight_decay 0.0001 --lr 1e-06 --epochs 20 --epochs_since_improvement 5 --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --model_name "vinai/bertweet-base" --exp_id hp_search_moji_bertweet_bal/fairlib_bert_moji_vanilla_1/5_16_1e-06_0.0001 --device_id 1&
python fairlib --dataset Moji --emb_size 768 --num_classes 2 --encoder_architecture BERT --batch_size 16 --test_batch_size 32 --dropout 0.1 --weight_decay 0 --lr 5e-06 --epochs 20 --epochs_since_improvement 5 --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --model_name "vinai/bertweet-base" --exp_id hp_search_moji_bertweet_bal/fairlib_bert_moji_vanilla_1/5_16_5e-06_0 --device_id 2; wait
python fairlib --dataset Moji --emb_size 768 --num_classes 2 --encoder_architecture BERT --batch_size 16 --test_batch_size 32 --dropout 0.1 --weight_decay 0.0001 --lr 5e-06 --epochs 20 --epochs_since_improvement 5 --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --model_name "vinai/bertweet-base" --exp_id hp_search_moji_bertweet_bal/fairlib_bert_moji_vanilla_1/5_16_5e-06_0.0001 --device_id 0&
python fairlib --dataset Moji --emb_size 768 --num_classes 2 --encoder_architecture BERT --batch_size 16 --test_batch_size 32 --dropout 0.1 --weight_decay 0 --lr 1e-05 --epochs 20 --epochs_since_improvement 5 --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --model_name "vinai/bertweet-base" --exp_id hp_search_moji_bertweet_bal/fairlib_bert_moji_vanilla_1/5_16_1e-05_0 --device_id 1&
python fairlib --dataset Moji --emb_size 768 --num_classes 2 --encoder_architecture BERT --batch_size 16 --test_batch_size 32 --dropout 0.1 --weight_decay 0.0001 --lr 1e-05 --epochs 20 --epochs_since_improvement 5 --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --model_name "vinai/bertweet-base" --exp_id hp_search_moji_bertweet_bal/fairlib_bert_moji_vanilla_1/5_16_1e-05_0.0001 --device_id 2; wait
python fairlib --dataset Moji --emb_size 768 --num_classes 2 --encoder_architecture BERT --batch_size 16 --test_batch_size 32 --dropout 0.1 --weight_decay 0 --lr 3e-05 --epochs 20 --epochs_since_improvement 5 --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --model_name "vinai/bertweet-base" --exp_id hp_search_moji_bertweet_bal/fairlib_bert_moji_vanilla_1/5_16_3e-05_0 --device_id 0&
python fairlib --dataset Moji --emb_size 768 --num_classes 2 --encoder_architecture BERT --batch_size 16 --test_batch_size 32 --dropout 0.1 --weight_decay 0.0001 --lr 3e-05 --epochs 20 --epochs_since_improvement 5 --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --model_name "vinai/bertweet-base" --exp_id hp_search_moji_bertweet_bal/fairlib_bert_moji_vanilla_1/5_16_3e-05_0.0001 --device_id 1&
python fairlib --dataset Moji --emb_size 768 --num_classes 2 --encoder_architecture BERT --batch_size 16 --test_batch_size 32 --dropout 0.1 --weight_decay 0 --lr 5e-05 --epochs 20 --epochs_since_improvement 5 --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --model_name "vinai/bertweet-base" --exp_id hp_search_moji_bertweet_bal/fairlib_bert_moji_vanilla_1/5_16_5e-05_0 --device_id 2; wait
python fairlib --dataset Moji --emb_size 768 --num_classes 2 --encoder_architecture BERT --batch_size 16 --test_batch_size 32 --dropout 0.1 --weight_decay 0.0001 --lr 5e-05 --epochs 20 --epochs_since_improvement 5 --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --model_name "vinai/bertweet-base" --exp_id hp_search_moji_bertweet_bal/fairlib_bert_moji_vanilla_1/5_16_5e-05_0.0001 --device_id 0&
python fairlib --dataset Moji --emb_size 768 --num_classes 2 --encoder_architecture BERT --batch_size 32 --test_batch_size 32 --dropout 0.1 --weight_decay 0 --lr 1e-06 --epochs 20 --epochs_since_improvement 5 --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --model_name "vinai/bertweet-base" --exp_id hp_search_moji_bertweet_bal/fairlib_bert_moji_vanilla_1/5_32_1e-06_0 --device_id 1&
python fairlib --dataset Moji --emb_size 768 --num_classes 2 --encoder_architecture BERT --batch_size 32 --test_batch_size 32 --dropout 0.1 --weight_decay 0.0001 --lr 1e-06 --epochs 20 --epochs_since_improvement 5 --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --model_name "vinai/bertweet-base" --exp_id hp_search_moji_bertweet_bal/fairlib_bert_moji_vanilla_1/5_32_1e-06_0.0001 --device_id 2; wait
python fairlib --dataset Moji --emb_size 768 --num_classes 2 --encoder_architecture BERT --batch_size 32 --test_batch_size 32 --dropout 0.1 --weight_decay 0 --lr 5e-06 --epochs 20 --epochs_since_improvement 5 --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --model_name "vinai/bertweet-base" --exp_id hp_search_moji_bertweet_bal/fairlib_bert_moji_vanilla_1/5_32_5e-06_0 --device_id 0&
python fairlib --dataset Moji --emb_size 768 --num_classes 2 --encoder_architecture BERT --batch_size 32 --test_batch_size 32 --dropout 0.1 --weight_decay 0.0001 --lr 5e-06 --epochs 20 --epochs_since_improvement 5 --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --model_name "vinai/bertweet-base" --exp_id hp_search_moji_bertweet_bal/fairlib_bert_moji_vanilla_1/5_32_5e-06_0.0001 --device_id 1&
python fairlib --dataset Moji --emb_size 768 --num_classes 2 --encoder_architecture BERT --batch_size 32 --test_batch_size 32 --dropout 0.1 --weight_decay 0 --lr 1e-05 --epochs 20 --epochs_since_improvement 5 --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --model_name "vinai/bertweet-base" --exp_id hp_search_moji_bertweet_bal/fairlib_bert_moji_vanilla_1/5_32_1e-05_0 --device_id 2; wait
python fairlib --dataset Moji --emb_size 768 --num_classes 2 --encoder_architecture BERT --batch_size 32 --test_batch_size 32 --dropout 0.1 --weight_decay 0.0001 --lr 1e-05 --epochs 20 --epochs_since_improvement 5 --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --model_name "vinai/bertweet-base" --exp_id hp_search_moji_bertweet_bal/fairlib_bert_moji_vanilla_1/5_32_1e-05_0.0001 --device_id 0&
python fairlib --dataset Moji --emb_size 768 --num_classes 2 --encoder_architecture BERT --batch_size 32 --test_batch_size 32 --dropout 0.1 --weight_decay 0 --lr 3e-05 --epochs 20 --epochs_since_improvement 5 --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --model_name "vinai/bertweet-base" --exp_id hp_search_moji_bertweet_bal/fairlib_bert_moji_vanilla_1/5_32_3e-05_0 --device_id 1&
python fairlib --dataset Moji --emb_size 768 --num_classes 2 --encoder_architecture BERT --batch_size 32 --test_batch_size 32 --dropout 0.1 --weight_decay 0.0001 --lr 3e-05 --epochs 20 --epochs_since_improvement 5 --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --model_name "vinai/bertweet-base" --exp_id hp_search_moji_bertweet_bal/fairlib_bert_moji_vanilla_1/5_32_3e-05_0.0001 --device_id 2; wait
python fairlib --dataset Moji --emb_size 768 --num_classes 2 --encoder_architecture BERT --batch_size 32 --test_batch_size 32 --dropout 0.1 --weight_decay 0 --lr 5e-05 --epochs 20 --epochs_since_improvement 5 --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --model_name "vinai/bertweet-base" --exp_id hp_search_moji_bertweet_bal/fairlib_bert_moji_vanilla_1/5_32_5e-05_0 --device_id 0&
python fairlib --dataset Moji --emb_size 768 --num_classes 2 --encoder_architecture BERT --batch_size 32 --test_batch_size 32 --dropout 0.1 --weight_decay 0.0001 --lr 5e-05 --epochs 20 --epochs_since_improvement 5 --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --model_name "vinai/bertweet-base" --exp_id hp_search_moji_bertweet_bal/fairlib_bert_moji_vanilla_1/5_32_5e-05_0.0001 --device_id 1; wait






# now unbal
python fairlib --dataset Moji --emb_size 768 --num_classes 2 --encoder_architecture BERT --batch_size 16 --test_batch_size 32 --dropout 0.1 --weight_decay 0 --lr 1e-06 --epochs 20 --unbalance_test --epochs_since_improvement 5 --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --model_name "vinai/bertweet-base" --exp_id hp_search_moji_bertweet_unbal/fairlib_bert_moji_vanilla_1/5_16_1e-06_0 --device_id 0&
python fairlib --dataset Moji --emb_size 768 --num_classes 2 --encoder_architecture BERT --batch_size 16 --test_batch_size 32 --dropout 0.1 --weight_decay 0.0001 --lr 1e-06 --epochs 20 --unbalance_test --epochs_since_improvement 5 --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --model_name "vinai/bertweet-base" --exp_id hp_search_moji_bertweet_unbal/fairlib_bert_moji_vanilla_1/5_16_1e-06_0.0001 --device_id 1&
python fairlib --dataset Moji --emb_size 768 --num_classes 2 --encoder_architecture BERT --batch_size 16 --test_batch_size 32 --dropout 0.1 --weight_decay 0 --lr 5e-06 --epochs 20 --unbalance_test --epochs_since_improvement 5 --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --model_name "vinai/bertweet-base" --exp_id hp_search_moji_bertweet_unbal/fairlib_bert_moji_vanilla_1/5_16_5e-06_0 --device_id 2; wait
python fairlib --dataset Moji --emb_size 768 --num_classes 2 --encoder_architecture BERT --batch_size 16 --test_batch_size 32 --dropout 0.1 --weight_decay 0.0001 --lr 5e-06 --epochs 20 --unbalance_test --epochs_since_improvement 5 --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --model_name "vinai/bertweet-base" --exp_id hp_search_moji_bertweet_unbal/fairlib_bert_moji_vanilla_1/5_16_5e-06_0.0001 --device_id 0&
python fairlib --dataset Moji --emb_size 768 --num_classes 2 --encoder_architecture BERT --batch_size 16 --test_batch_size 32 --dropout 0.1 --weight_decay 0 --lr 1e-05 --epochs 20 --unbalance_test --epochs_since_improvement 5 --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --model_name "vinai/bertweet-base" --exp_id hp_search_moji_bertweet_unbal/fairlib_bert_moji_vanilla_1/5_16_1e-05_0 --device_id 1&
python fairlib --dataset Moji --emb_size 768 --num_classes 2 --encoder_architecture BERT --batch_size 16 --test_batch_size 32 --dropout 0.1 --weight_decay 0.0001 --lr 1e-05 --epochs 20 --unbalance_test --epochs_since_improvement 5 --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --model_name "vinai/bertweet-base" --exp_id hp_search_moji_bertweet_unbal/fairlib_bert_moji_vanilla_1/5_16_1e-05_0.0001 --device_id 2; wait
python fairlib --dataset Moji --emb_size 768 --num_classes 2 --encoder_architecture BERT --batch_size 16 --test_batch_size 32 --dropout 0.1 --weight_decay 0 --lr 3e-05 --epochs 20 --unbalance_test --epochs_since_improvement 5 --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --model_name "vinai/bertweet-base" --exp_id hp_search_moji_bertweet_unbal/fairlib_bert_moji_vanilla_1/5_16_3e-05_0 --device_id 0&
python fairlib --dataset Moji --emb_size 768 --num_classes 2 --encoder_architecture BERT --batch_size 16 --test_batch_size 32 --dropout 0.1 --weight_decay 0.0001 --lr 3e-05 --epochs 20 --unbalance_test --epochs_since_improvement 5 --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --model_name "vinai/bertweet-base" --exp_id hp_search_moji_bertweet_unbal/fairlib_bert_moji_vanilla_1/5_16_3e-05_0.0001 --device_id 1&
python fairlib --dataset Moji --emb_size 768 --num_classes 2 --encoder_architecture BERT --batch_size 16 --test_batch_size 32 --dropout 0.1 --weight_decay 0 --lr 5e-05 --epochs 20 --unbalance_test --epochs_since_improvement 5 --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --model_name "vinai/bertweet-base" --exp_id hp_search_moji_bertweet_unbal/fairlib_bert_moji_vanilla_1/5_16_5e-05_0 --device_id 2; wait
python fairlib --dataset Moji --emb_size 768 --num_classes 2 --encoder_architecture BERT --batch_size 16 --test_batch_size 32 --dropout 0.1 --weight_decay 0.0001 --lr 5e-05 --epochs 20 --unbalance_test --epochs_since_improvement 5 --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --model_name "vinai/bertweet-base" --exp_id hp_search_moji_bertweet_unbal/fairlib_bert_moji_vanilla_1/5_16_5e-05_0.0001 --device_id 0&
python fairlib --dataset Moji --emb_size 768 --num_classes 2 --encoder_architecture BERT --batch_size 32 --test_batch_size 32 --dropout 0.1 --weight_decay 0 --lr 1e-06 --epochs 20 --unbalance_test --epochs_since_improvement 5 --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --model_name "vinai/bertweet-base" --exp_id hp_search_moji_bertweet_unbal/fairlib_bert_moji_vanilla_1/5_32_1e-06_0 --device_id 1&
python fairlib --dataset Moji --emb_size 768 --num_classes 2 --encoder_architecture BERT --batch_size 32 --test_batch_size 32 --dropout 0.1 --weight_decay 0.0001 --lr 1e-06 --epochs 20 --unbalance_test --epochs_since_improvement 5 --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --model_name "vinai/bertweet-base" --exp_id hp_search_moji_bertweet_unbal/fairlib_bert_moji_vanilla_1/5_32_1e-06_0.0001 --device_id 2; wait
python fairlib --dataset Moji --emb_size 768 --num_classes 2 --encoder_architecture BERT --batch_size 32 --test_batch_size 32 --dropout 0.1 --weight_decay 0 --lr 5e-06 --epochs 20 --unbalance_test --epochs_since_improvement 5 --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --model_name "vinai/bertweet-base" --exp_id hp_search_moji_bertweet_unbal/fairlib_bert_moji_vanilla_1/5_32_5e-06_0 --device_id 0&
python fairlib --dataset Moji --emb_size 768 --num_classes 2 --encoder_architecture BERT --batch_size 32 --test_batch_size 32 --dropout 0.1 --weight_decay 0.0001 --lr 5e-06 --epochs 20 --unbalance_test --epochs_since_improvement 5 --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --model_name "vinai/bertweet-base" --exp_id hp_search_moji_bertweet_unbal/fairlib_bert_moji_vanilla_1/5_32_5e-06_0.0001 --device_id 1&
python fairlib --dataset Moji --emb_size 768 --num_classes 2 --encoder_architecture BERT --batch_size 32 --test_batch_size 32 --dropout 0.1 --weight_decay 0 --lr 1e-05 --epochs 20 --unbalance_test --epochs_since_improvement 5 --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --model_name "vinai/bertweet-base" --exp_id hp_search_moji_bertweet_unbal/fairlib_bert_moji_vanilla_1/5_32_1e-05_0 --device_id 2; wait
python fairlib --dataset Moji --emb_size 768 --num_classes 2 --encoder_architecture BERT --batch_size 32 --test_batch_size 32 --dropout 0.1 --weight_decay 0.0001 --lr 1e-05 --epochs 20 --unbalance_test --epochs_since_improvement 5 --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --model_name "vinai/bertweet-base" --exp_id hp_search_moji_bertweet_unbal/fairlib_bert_moji_vanilla_1/5_32_1e-05_0.0001 --device_id 0&
python fairlib --dataset Moji --emb_size 768 --num_classes 2 --encoder_architecture BERT --batch_size 32 --test_batch_size 32 --dropout 0.1 --weight_decay 0 --lr 3e-05 --epochs 20 --unbalance_test --epochs_since_improvement 5 --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --model_name "vinai/bertweet-base" --exp_id hp_search_moji_bertweet_unbal/fairlib_bert_moji_vanilla_1/5_32_3e-05_0 --device_id 1&
python fairlib --dataset Moji --emb_size 768 --num_classes 2 --encoder_architecture BERT --batch_size 32 --test_batch_size 32 --dropout 0.1 --weight_decay 0.0001 --lr 3e-05 --epochs 20 --unbalance_test --epochs_since_improvement 5 --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --model_name "vinai/bertweet-base" --exp_id hp_search_moji_bertweet_unbal/fairlib_bert_moji_vanilla_1/5_32_3e-05_0.0001 --device_id 2; wait
python fairlib --dataset Moji --emb_size 768 --num_classes 2 --encoder_architecture BERT --batch_size 32 --test_batch_size 32 --dropout 0.1 --weight_decay 0 --lr 5e-05 --epochs 20 --unbalance_test --epochs_since_improvement 5 --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --model_name "vinai/bertweet-base" --exp_id hp_search_moji_bertweet_unbal/fairlib_bert_moji_vanilla_1/5_32_5e-05_0 --device_id 0&
python fairlib --dataset Moji --emb_size 768 --num_classes 2 --encoder_architecture BERT --batch_size 32 --test_batch_size 32 --dropout 0.1 --weight_decay 0.0001 --lr 5e-05 --epochs 20 --unbalance_test --epochs_since_improvement 5 --data_dir ../fl_scripts/data/deepmoji --base_seed 1 --model_name "vinai/bertweet-base" --exp_id hp_search_moji_bertweet_unbal/fairlib_bert_moji_vanilla_1/5_32_5e-05_0.0001 --device_id 1; wait
